### ISSUE TITLE
Load more comments error

### ISSUE THREAD

**Issue by pkanodia** [mattbdean/JRAW#169]
commentNode.loadMoreComments(reddit) throws Request returned non-successful status code: 756 Too long request string.

//the calling method
Submission submission = redditClient.getSubmission(request);
					CommentNode rootNode = submission.getComments();
loadFully(redditClient, depthNo, requestLimit, rootNode);

private void loadFully(RedditClient reddit, int depthLimit, int requestLimit, CommentNode commentNode)
			throws NetworkException, InterruptedException {

		int requests = 0;
		if (depthLimit < CommentNode.NO_LIMIT || requestLimit < CommentNode.NO_LIMIT)
			throw new IllegalArgumentException(
					"Expecting a number greater than or equal to -1, got " + (requestLimit < CommentNode.NO_LIMIT ? requestLimit : depthLimit));
		// Load this node's comments first
		while (commentNode.hasMoreComments()) {
                       //below method throws the exceptions
			commentNode.loadMoreComments(reddit);
			if (++requests > requestLimit && depthLimit != CommentNode.NO_LIMIT)
				return;
			Thread.sleep(1000);
		}

		// Load the children's comments next
		for (CommentNode node : commentNode.walkTree(TraversalMethod.BREADTH_FIRST)) {
			// Travel breadth first so we can accurately compare depths
			if (depthLimit != CommentNode.NO_LIMIT && node.getDepth() > depthLimit)
				return;
			while (node.hasMoreComments()) {
				node.loadMoreComments(reddit);
				if (++requests > requestLimit && depthLimit != CommentNode.NO_LIMIT)
					return;
				Thread.sleep(1000);
			}
		}
	}

**Comment by thatJavaNerd** [comment]
Can you provide the relevant code?

**Comment by pkanodia** [comment]
On debugging found that error - "**Request returned non-successful status code: 756 Too long request string**" is being thrown by method - "**List<Thing> getMoreComments(RedditClient reddit)**" on line number 484 of https://github.com/thatJavaNerd/JRAW/blob/master/src/main/java/net/dean/jraw/models/CommentNode.java

https://www.reddit.com/dev/api/#GET_api_morechildren gives only 20 more comments at a time, but according to code we are sending ids of all the children. This is making the GET request URL very long if there are large number of comments.

**Comment by mattbdean** [comment]
Sorry it took so long, fixed with [`c4d1fac`](https://github.com/mattbdean/JRAW/commit/c12f141d94f29772298a0afbd3f565ce85051800#diff-c4d1face06dae528be6c7ac46d7b6ffbR76)
