### ISSUE TITLE
Best way to use this library on android (callback?)

### ISSUE THREAD

**Issue by josecostamartins** [mattbdean/JRAW#191]
So I've been wondering what's the best way to use the calls to this library, but so far I could not grasp it.

The majority of examples I could find uses the calls inside an AsyncTask, which is by no means the best way to implement this, it's a nightmare to deal with lifecycles inside asyncTasks (including, but not limited to, device rotation).

From my perspective, the calls could have a callback (an OKHttp callback for example)...

Is there any way you guys use this library other than inside an AsyncTask?

**Comment by thatJavaNerd** [comment]
@ccrama uses JRAW in Slide for Reddit, maybe he can weigh in on this.

**Comment by ccrama** [comment]
@thatJavaNerd Currently Slide uses a lot of AsyncTasks which are not ideal ( @josecostamartins 's comments on this were spot on), and I did a lot of work on keeping contexts alive and managing these open connections in case the lifecycle changes. My current plan is to re-do a lot of Slide's backend code to use RxJava after I finish the iOS app and stray away from AsyncTasks.

I was actually going to comment on this in the Android Improvement thread @thatJavaNerd , but OkHTTP already works pretty well with RxJava observables, and some examples using RxJava for Android might be helpful for new users of JRAW.

Some good links information RxJava and integration with OkHTTP can be found here

https://stackoverflow.com/questions/32687921/using-rxjava-and-okhttp
https://github.com/ReactiveX/RxJava

JRAW is structured in a way that would let the observables be pretty abstract (using Paginators or Things), so implementing this from the start should be pretty easy as long as you have a decent idea about how RXJava and Observable work, but an example would still be helpful!

**Comment by thatJavaNerd** [comment]
I thought about baking RxJava in for v1.0.0 but I wasn't sure how useful it would be. Could you give an example on how this would work?

**Comment by josecostamartins** [comment]
Yes, although I don't know RxJava or reactive programming, it seems a reasonable way to go (with some modifications to the library, I suppose).

Another way that I thought is to use a centralized queue (running in a background thread) that will run the action (or the job) and serialize the data, then with the use of an event bus (or a broadcast receiver) warn the interested components that the data is ready to be used (this can be accomplished with: https://github.com/yigit/android-priority-jobqueue)

Again, I believe that architecturally both using reactive programming or job queue are similar (perform some action and warn me when it's done)

**Comment by Saketme** [comment]
I find event-bus architecture really bad because there is no way for a person reading the code to follow the call hierarchy for methods. In a pub-sub pattern like RxJava, you can atleast view the usages for a publisher, which makes understanding a codebase quite easy.

**Comment by josecostamartins** [comment]
Yes, you are right. 
When a broadcast is sent (which is basically what an event bus is doing) each and every listener will be able to do something with that event, and if somebody is trying to read the code that may confuse them, but a comment can solve this issue. 

Other than that, a library should allow the user (in this case the developer) to choose the architecture that is most suitable for him/her, and not "force" the use of an entire component/programming paradigm. Unless, of course, it is a framework and not a library.

Please do not get me wrong, I do not have a problem with RxJava (other than the lack of knowledge). But not everybody wants to/can use RxJava in their apps, and the event bus architecture was proposed by me as an alternative answer to the question of how to use JRAW with Android.

**Comment by Saketme** [comment]
> Other than that, a library should allow the user (in this case the developer) to choose the architecture that is most suitable for him/her, and not "force" the use of an entire component/programming paradigm. Unless, of course, it is a framework and not a library.

Agreed.
