### ISSUE TITLE
Android example missing?

### ISSUE THREAD

**Issue by karanrajpal14** [mattbdean/JRAW#194]
I've been going through your Quick start guide and trying my best to understand how OAuth works but I'm not able to. 
Could you please update the docs to have a small sample of how it would work with Android as your current link on [this](https://github.com/mattbdean/JRAW/wiki/OAuth2) page is dead and it asks me to create a new wiki when I click on the Android example.

The fact that the Reddit documentation is a bit vague about this is of help either. Certainly not for a beginner. Would you please help me out here? Thank you!

**Comment by jorgegil96** [comment]
[Here's a small sample](https://github.com/jorgegil96/JRAW-Android-Sample) I wrote up that shows the authentication flow with and without user context. I'm using RxJava for the network calls but you can obviously use whatever you prefer.

Note that tokens expire after a while so you have to call AuthenticationManager.refreshAccessToken() to refresh them. You can see if your token is still valid with AuthenticationManager.checkAuthState().

**Comment by karanrajpal14** [comment]
Thank you for this. I'll give it a shot! I'll probably have to rewrite the networking part since I don't know RxJava and replace it with Retrtofit. Nevertheless, thank you!
