### ISSUE TITLE
Issue with ModAction target_author.

### ISSUE THREAD

**Issue by LearningMonkey** [mattbdean/JRAW#195]
Pretty sure this has to be a mistake.

ModAction.getTargetAuthor() was returning null for me. I only noticed after saving lots of data. Anyway, some reason the code says:

`   @JsonProperty
    public String getTargetAuthor() {
        return data("jraw_test");
    }`

ModAction.getDataNode().get("target_author").asText() works fine.

**Comment by mattbdean** [comment]
Oh dear...

Yes this is a mistake, thanks for letting me know
