### ISSUE TITLE
CommentNode#equals() results in an infinite loop

### ISSUE THREAD

**Issue by Saketme** [mattbdean/JRAW#197]
Hey @mattbdean, I'm using [DiffUtils](https://developer.android.com/reference/android/support/v7/util/DiffUtil.html) when displaying comments in my app for animating changes. I'm seeing a problem where calling `equals()` on the same `CommentNode` is resulting in an infinite loop. 

~I'm not sure if I understand this correctly, but `CommentNode#equals()` calls equals on both its~
~parent node and its children node, which ends in an endless loop.~

Update: something else is triggering an infinite loop. Matt, does this sound familiar to you?

**Comment by mattbdean** [comment]
My first thought would be that [this line](https://github.com/mattbdean/JRAW/blob/3d7e45e83df852f1fb2631d77841aa0e79c73c8e/src/main/java/net/dean/jraw/models/CommentNode.java#L637) is causing it like you suggested. How'd you rule that out?

**Comment by Saketme** [comment]
Because I replaced `parent.equals(that.parent)` with `parent.comment.getFullName().equals(that.parent.comment.getFullName())` and the error was still there.

**Comment by mattbdean** [comment]
Can you post the relevant code?

**Comment by Saketme** [comment]
@mattbdean are you referring to my DiffUtils implementation? or the modified `CommentNode#equals()`?

**Comment by mattbdean** [comment]
Both

**Comment by mattbdean** [comment]
@Saketme did you ever figure out the issue?

**Comment by Saketme** [comment]
Whoops, I totally forgot about this issue. I could not figure out what exactly was triggering the loop, because I eventually ended up changing my implementation which depended on this :(
