### ISSUE TITLE
Subreddit Streams

### ISSUE THREAD

**Issue by Tello-Wharton** [mattbdean/JRAW#200]
Is there functionality in this project for subreddit streams in a similar fashion to what PRAW can achieve?

http://praw.readthedocs.io/en/latest/code_overview/models/subreddit.html

for comment in reddit.subreddit('iama').stream.comments():
    print(comment)

**Comment by mattbdean** [comment]
Not exactly. We can get close to this behavior using Paginators.

For v0.9.0:

```java
Paginator<Comment> stream = new CommentStream(redditClient, "<subreddit>");
stream.setSorting(Sorting.NEW);
stream.setLimit(Paginator.RECOMMENDED_MAX_LIMIT); // 100 items per page

for (Listing<Comment> page : stream) {
    // <do something with page>
    // Reset the Paginator to fetch the first page
    stream.reset();
}
```

For v1.0.0 (currently unreleased)

```java
BarebonesPaginator<Comment> stream = redditClient.latestComments("<subreddit>")
    .limit(Paginator.RECOMMENDED_MAX_LIMIT)
    .build();

for (Listing<Comment> page : stream) {
    // <do something with page>
    // Reset the Paginator to fetch the first page
    stream.restart();
}
```

This isn't perfect -- if more comments are created faster than you can request them you're going to miss out on some data. If the opposite is true, you'll get some duplicate comments.

**Comment by Tello-Wharton** [comment]
No worries, thanks!
