### ISSUE TITLE
Does JRAW use the JSON API?

### ISSUE THREAD

**Issue by Obaied** [mattbdean/JRAW#201]
Hey all
Does JRAW support fetching posts using Reddit's [JSON API](https://github.com/reddit/reddit/wiki/JSON)?

**Comment by mattbdean** [comment]
Yes, here's an example of front page iteration:

```java
// Set up a Paginator for the front page
SubredditPaginator paginator = new SubredditPaginator(redditClient);
// Request the first page
Listing<Submission> firstPage = paginator.next();

// Iterate over the submissions
for (Submission submission : firstPage) {
    // do something
}
```

You might also want to take a look at the [quickstart](https://github.com/mattbdean/JRAW/wiki/Quickstart) if you're new.

**Comment by Obaied** [comment]
Thanks!!
