### ISSUE TITLE
How can I get the submission age

### ISSUE THREAD

**Issue by mpivchev** [mattbdean/JRAW#203]
I can't figure out how I can get the age of a submission (like posted "7 hours ago"). Any ideas?

**Comment by mattbdean** [comment]
`submission.getCreated()` will give you a `java.util.Date` object. There are a few libraries that will format it for you ([JodaTime](http://www.joda.org/joda-time/), [PrettyTime](http://www.ocpsoft.org/prettytime/))

See [here](https://stackoverflow.com/q/3859288/1275092) for more.
