### ISSUE TITLE
Getting submission flair color

### ISSUE THREAD

**Issue by mpivchev** [mattbdean/JRAW#205]
I can get the text but I can't figure out how to get the color (foreground and background). I know I can use `getStylesheet` but that doesn't work for the front page, since it contains a lot of subreddits. Any idea?

**Comment by mattbdean** [comment]
I didn't think `getStylesheet` worked for the front page. It requests [this link](https://api.reddit.com/stylesheet), which 404's. To figure out flair colors you'd have to request and parse the stylesheet for the post's subreddit. You should be able to identify which classes reddit uses for flair from the [/r/csshelp wiki](https://www.reddit.com/r/csshelp/wiki/index).
