### ISSUE TITLE
Get part of CommentNode with submission ID and comment ID

### ISSUE THREAD

**Issue by ArnoCo** [mattbdean/JRAW#208]
Is there already a way to go to a single comment thread [like this](https://www.reddit.com/r/mildlyinteresting/comments/7lm8ps/a_carton_of_egg/drnkq80/?context=4)? 

Currently I have to get the entire submission and then .findChild() with the unique comment ID. Which is quite annoying when working with big threads as they'll require a loadFully() before being able to .findChild() with 100% certainty.

**Comment by eduard-netsajev** [comment]
Not sure if this feature is implemented (it isn't as far as I know), but one of the solutions using existing API would be to load a single comment, get its parent's full name, load that comment, and do so as many times as you need or want (per the context query argument, e.g. the link you provided specifies the context to be 4 messages long).

Even though it would take a lot more requests than it should (using the available Reddit API), it would be much more efficient in a lot of cases than using `loadFully()`

**Comment by ArnoCo** [comment]
@eduard-netsajev 
`would be to load a single comment`

what exactly do you mean by that? Because I personally don't know how I'd go about doing that. A SubmissionRequest only accepts _submission ID_ not a _comment ID_, correct?

**Comment by mattbdean** [comment]
For v0.9.0:

```java
Submission post = redditClient.getSubission(new SubmissionRequest.Builder("7lm8ps")
    .context(4)
    .focus("drnkq80")
    .build());
```

For v1.0.0 (`master` branch):

```java
RootCommentNode root = redditClient
    .submission("7lm8ps")
    .comments(new CommentsRequest.Builder()
        .context(4)
        .focus("drnkq80")
        .build());
```

Both will request this link: [`https://www.reddit.com/comments/7lm8ps?comment=drnkq80&context=4`](https://www.reddit.com/comments/7lm8ps?comment=drnkq80&context=4).

Sources: [`SubmissionRequest`](https://github.com/mattbdean/JRAW/blob/v0.9.0/src/main/java/net/dean/jraw/http/SubmissionRequest.java), [`CommentsRequest`](https://github.com/mattbdean/JRAW/blob/53bdda360495e7e5460ee286e6dec88bc3f8716b/lib/src/main/kotlin/net/dean/jraw/references/CommentsRequest.kt)

**Comment by ArnoCo** [comment]
Perfect! I was already looking around using 'focus()' but couldn't get it to work correctly. Thanks a lot for the quick reply matt.
