### ISSUE TITLE
Outputting To Console

### ISSUE THREAD

**Issue by JRascagneres** [mattbdean/JRAW#209]
Not sure if its an issue exactly but when making requests it prints everythint to console whenever I connect or get data. Posting the GET requests and the returns.
Is there a way to surpress?

**Comment by mattbdean** [comment]
What version are you using?

**Comment by JRascagneres** [comment]
1.0.0

**Comment by mattbdean** [comment]
Set `logHttp` to false. For Kotlin:

```kotlin
redditClient.logHttp = false
```

For Java:

```java
redditClient.setLogHttp(false);
```

**Comment by JRascagneres** [comment]
Thanks!
