### ISSUE TITLE
Comments from multiple subreddits

### ISSUE THREAD

**Issue by lulzmachine** [mattbdean/JRAW#211]
Hello!

I'm using jraw version 1.0.0

I'm trying to get comments from multiple subreddits. When getting comments for one, I do this:
```
    var r = reddit.subreddit("first").comments().build();
```

But when trying to do the same thing for multiple subscriptions I face this:
```
    var r = reddit.subreddits("first", "second").comments().build(); // <--- unresolved reference "comments"
```

I found the reason in the source code in RedditClient.kt on line 301:
```
    fun subreddits(first: String, second: String, vararg others: String) =
        SubredditReference(this, arrayOf(first, second, *others).joinToString("+")).posts()
```

The fact that subreddit returns a SubredditReference but subreddit**s** returns a posts iterator seems confusing. Is there a way for me to get comments for multiple subreddits?

As a temporary solution I borrowed the code from RedditClient, and did this: ```reddit.subreddit(arrayOf("btc", "bitcoin").joinToString("+")).comments().build();``` which works fine, but seems like I'm working against the library.

**Comment by mattbdean** [comment]
You're right, that is pretty confusing. I'm going to take `.posts()` off of the body of `subreddits` so that it returns a SubredditReference instead of jumping right to the posts:

```kt
fun subreddits(first: String, second: String, vararg others: String) =
    SubredditReference(this, arrayOf(first, second, *others).joinToString("+"))
```

For now you should continue using `arrayOf(...).joinToString("+")` until this gets patched in 1.1.0

**Comment by mattbdean** [comment]
Fixed. You can continue to use your solution and wait until 1.1.0 or use JitPack:

```groovy
repositories {
    maven { url 'https://jitpack.io' }
}
dependencies {
    compile 'com.github.mattbdean:JRAW:998642f2db'
}
```

**Comment by lulzmachine** [comment]
Thanks for the quick response and an awesome library!
