### ISSUE TITLE
Support the 'web' OAuth2 app type

### ISSUE THREAD

**Issue by mattbdean** [mattbdean/JRAW#213]
Right now OAuthHelper.interactive throws a `NotImplementedError` when [given webapp Credentials](https://github.com/mattbdean/JRAW/blob/v1.0.0/lib/src/main/kotlin/net/dean/jraw/oauth/OAuthHelper.kt#L50). Shouldn't be too hard to get this working. It'll require us to have more data in credentials.json

 - [ ] Add appropriate code to OAuthHelper.interactive and expand OAuthHelper tests
 - [ ] Update the readme, specifically the section about the shape of `credentials.json`
 - [ ] Update `:meta:credentials` to generate an OAuth2 app of type `web`

**Comment by koflin** [comment]
Is this now implemented in v1.1.0 ?

**Comment by mattbdean** [comment]
Yep
