### ISSUE TITLE
Unable to merge dex

### ISSUE THREAD

**Issue by mpivchev** [mattbdean/JRAW#218]
Trying to compile two of your dependencies gives me the following error:

```
Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
```

Here are the dependencies:

```
    compile 'com.github.mattbdean:JRAW:6977732'
    implementation 'net.dean.jraw:JRAW-Android:1.0.0'
```

I tried cleaning, rebuilding, adding `multiDexEnabled true` to the defaultConfig but it still gives me the error

P.S. Also tried it on your Android app demo, same thing happens

**Comment by mattbdean** [comment]
Without a stacktrace, I can only assume that its a dependency issue.

JRAW-Android depends on JRAW, so you're including it twice. Try this:

```groovy
implementation 'com.github.mattbdean:JRAW:6977732'
implementation('net.dean.jraw:JRAW-Android:1.0.0') {
    exclude group: 'net.dean.jraw'
}
```

If this doesn't fix it, can you post the stacktrace?

```
$ ./gradlew <task> --stacktrace`
```

**Comment by mpivchev** [comment]
Works fine now, thanks!
