### ISSUE TITLE
Submission as a Parcelable

### ISSUE THREAD

**Issue by mpivchev** [mattbdean/JRAW#221]
I would like to pass the selected Submission to another activity, but I can see that Submission does not implement `Parcelable`. Is there a way to serialize it without using some fancy library?

**Comment by mattbdean** [comment]
The best non-Android specific way to fix this would have the model classes implement Serializable. I'll update the code when I get a chance.

**Comment by mpivchev** [comment]
Isn't it better for the model to implement Parcelable since it's much faster for Android?

**Comment by mattbdean** [comment]
That is the better solution, but JRAW is not an Android library (which is why [JRAW-Android](https://github.com/mattbdean/JRAW-Android) exists). The simplest solution would be Serializable.

**Comment by mpivchev** [comment]
Hmm, it would be great if there can be a SubmissionSerializable and SubmissionParcelable for each platform but I don't know how long that would take to implement

**Comment by mattbdean** [comment]
That method would get very messy very quick. Also check out #204.

**Comment by Saketme** [comment]
Why are you against using a library which will solve this problem in just a few lines for you, @mpivchev?

**Comment by mpivchev** [comment]
@Saketme I want to use as few libraries as possible because most of them take up a lot of space, but I guess I don't have a choice in this regard. What can you suggest me use for serialization?

**Comment by mattbdean** [comment]
Well you could just use the Moshi adapter `JrawUtils.moshi` to serialize/deserialize. It can deserialize everything but serializing it might be an issue for certain models.

**Comment by mpivchev** [comment]
@mattbdean Can you provide some example code for serializing and deserializing submissions? I have never used Moshi before and I am not sure how to do it.

**Comment by Saketme** [comment]
Untested, but this should work:

```
Moshi moshi = new Moshi.Builder()
  .add(ModelAdapterFactory.create())
  .build();

JsonAdapter<Submission> jsonAdapter = moshi.adapter(Submission.class);
String serialized = jsonAdapter.toJson(submission);
Submission deserialized = jsonAdapter.fromJson(serialized);
```

**Comment by mattbdean** [comment]
You can also use the Moshi instance JRAW uses internally: `JrawUtils.moshi`

**Comment by mpivchev** [comment]
For some  reason, it throws a `NullPointerException: Null distinguished`

```
  JsonAdapter<Submission> jsonAdapter = JrawUtils.moshi.adapter(Submission.class);
            String serializedSubmission = jsonAdapter.toJson(submission);

            Intent intent = new Intent(getActivity(), SubmissionActivity.class);
            intent.putExtra("submissionSerialized", serializedSubmission);
            startActivity(intent);
```

```
   JsonAdapter<Submission> jsonAdapter = JrawUtils.moshi.adapter(Submission.class);

        if (getActivity() != null && getActivity().getIntent().getExtras() != null) {
            //This is not null, since it shows on the log
            String serializedSubmission = getActivity().getIntent().getExtras().getString("submissionSerialized"); 
            
            try {
                if (serializedSubmission != null) {
                    submission = jsonAdapter.fromJson(serializedSubmission); //This is where it throws the error
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
```

**Comment by Saketme** [comment]
@mpivchev Can you post the JSON here?

**Comment by mpivchev** [comment]
```
{
"score":14288,
"saved":false,
"stickied":false,
"author":"mysticalmisogynistic",
"archived":false,
"can_gild":false,
"created_utc":1516722593,
"contest_mode":false,
"domain":"i.imgur.com",
"name":"t3_7sfa7x",
"gilded":0,
"hidden":false,
"hide_score":false,
"id":"7sfa7x",
"is_self":false,
"locked":false,
"over_18":false,
"permalink":"/r/ChoosingBeggars/comments/7sfa7x/quite_literally_choosing_beggar/",
"post_hint":"image",
"preview":{
"images":[
{
"source":{
"url":"https://i.redditmedia.com/Ypnm13TQXbgcB6k81cabqnuyMmaAs8d1_oxefPtgiGg.jpg?s=2f89802bab99ae1c667995df4299de77",
"width":1920,
"height":1080
},
"resolutions":[
{
"url":"https://i.redditmedia.com/Ypnm13TQXbgcB6k81cabqnuyMmaAs8d1_oxefPtgiGg.jpg?fit=crop&crop=faces%2Centropy&arh=2&w=108&s=871b789252c2f936194880f25d71aaa1",
"width":108,
"height":60
},
{
"url":"https://i.redditmedia.com/Ypnm13TQXbgcB6k81cabqnuyMmaAs8d1_oxefPtgiGg.jpg?fit=crop&crop=faces%2Centropy&arh=2&w=216&s=e2e1e0837cc2c3c94bb4ab137c165c02",
"width":216,
"height":121
},
{
"url":"https://i.redditmedia.com/Ypnm13TQXbgcB6k81cabqnuyMmaAs8d1_oxefPtgiGg.jpg?fit=crop&crop=faces%2Centropy&arh=2&w=320&s=a6f6aa205a072e5d88586cd7d99fbc59",
"width":320,
"height":180
},
{
"url":"https://i.redditmedia.com/Ypnm13TQXbgcB6k81cabqnuyMmaAs8d1_oxefPtgiGg.jpg?fit=crop&crop=faces%2Centropy&arh=2&w=640&s=bbdc53e5bfc318dcc600a245bbe14f75",
"width":640,
"height":360
},
{
"url":"https://i.redditmedia.com/Ypnm13TQXbgcB6k81cabqnuyMmaAs8d1_oxefPtgiGg.jpg?fit=crop&crop=faces%2Centropy&arh=2&w=960&s=f20b25c19540c5de9a3366634b63697d",
"width":960,
"height":540
},
{
"url":"https://i.redditmedia.com/Ypnm13TQXbgcB6k81cabqnuyMmaAs8d1_oxefPtgiGg.jpg?fit=crop&crop=faces%2Centropy&arh=2&w=1080&s=09fb2379aa206fd651c413f1a99c1685",
"width":1080,
"height":607
}
],
"id":"gMd4Q40I3MvBLcqgWosGaIdBSVexJZ0Xkb6N0uqDWes"
}
],
"enabled":true
},
"quarantine":false,
"selftext":"",
"spam":false,
"spoiler":false,
"subreddit":"ChoosingBeggars",
"subreddit_id":"t5_35fmc",
"thumbnail":"https://b.thumbs.redditmedia.com/iH9Re0oTMOiSlhEduVacFuqobmdPJ12EUd12OeFZZ8Y.jpg",
"title":"Quite literally choosing beggar",
"url":"https://i.imgur.com/T6002R3.jpg",
"visited":false,
"removed":false,
"num_comments":635
}
```

**Comment by mpivchev** [comment]
Any idea why this is happening?

**Comment by Saketme** [comment]
Sorry for the late reply. From what I can see, the `distinguished` field is annotated with `@NotNull`, which means AutoValue will not let a `Submission` instance be created without a value in the first place. So I'm unable to understand how you're able to reach this situation. I am out of ideas. Maybe @mattbdean will have an answer.

**Comment by mpivchev** [comment]
@mattbdean any update on this?

**Comment by mattbdean** [comment]
Not trying to ignore you, I'm drowning in school and work. I'll get back to you as soon as I'm able to!

**Comment by mattbdean** [comment]
reddit uses a null value for "distinguished" to represent a normal user. JRAW turns that null value into `DistinguishedStatus.NORMAL` [here](https://github.com/mattbdean/JRAW/blob/3770702af8c4a6aacd70a5b2636b6ed8fa7ca162/lib/src/main/kotlin/net/dean/jraw/databind/NullAwareEnumAdapters.kt#L69). Moshi doesn't serialize null values by default, so when we serialize the Submission, it leaves out `distinguished`. When the adapter goes to deserialize the JSON, it expects to find `"distinguished": null`, but finds nothing, so it never gets transformed into `DistinguishedStatus.NORMAL` and remains null. Since the distinguished property [is required to be non-null](https://github.com/mattbdean/JRAW/blob/5d1d6c5cdc36643d3e8492a5579e687b9cb32fe4/lib/src/main/java/net/dean/jraw/models/Submission.java#L39), AutoValue throws an error.

The simple fix here is to manually specifcy that Moshi serialize nulls. Here's a little test case:

```kotlin
val adapter = JrawUtils.adapter<Submission>().serializeNulls()

val subAsPojo = reddit.submission("7sfa7x").inspect()
val subAsJson = adapter.toJson(subAsPojo)
val recreated = adapter.fromJson(subAsJson)

subAsPojo.should.equal(recreated)
```

**Comment by mpivchev** [comment]
Thanks for the update. I'm gonna try this at the end of next week because university exams have me by the balls

**Comment by mattbdean** [comment]
I've made all models Serializable. I've also added a [new test](https://github.com/mattbdean/JRAW/blob/73312c11dbc7f16514db0113ccdd3666479b0c04/lib/src/test/kotlin/net/dean/jraw/test/unit/IntrospectiveTest.kt) that makes sure all new models we add are also Serializable.

**Comment by mpivchev** [comment]
Submissions get serialized properly now. Thanks!

**Comment by mattbdean** [comment]
I've also added a section in [JRAW-Android's readme](https://github.com/mattbdean/JRAW-Android#faq) about this since this seems to be pretty popular question
