### ISSUE TITLE
Question for reddit url

### ISSUE THREAD

**Issue by JRascagneres** [mattbdean/JRAW#223]
Hello,
How do I get the url of the reddit post? submission.url() will get the link the post actually links to not only the reddit post itself. How can I always get only the actual post?
Thanks

**Comment by mattbdean** [comment]
`submission.getPermalink()` will return something like `/r/RocketLeague/comments/7sh6dg/signups_for_rlcs_season_5_are_now_open/`, or you can use `"/comments/" + submission.getId()`, which will end up redirecting the user to that permalink anyway.
