### ISSUE TITLE
Make sure we're not using the deprecated reddit search engine

### ISSUE THREAD

**Issue by mattbdean** [mattbdean/JRAW#226]
The old search stack is being deprecated March 15. See [here](https://www.reddit.com/r/changelog/comments/7tus5f/update_to_search_api/) for more info. Not quite sure if we have to do anything yet, I just wanted to make the issue so I don't forget.

**Comment by ccrama** [comment]
I think JRAW is good, from the post:

> If you’re an author of an API client such as an app, bot, or other electronic sentience, your API client may be getting results from the older Cloudsearch-powered system because we’ve tried to avoid breaking tools that may be more sensitive to syntax changes while we worked on stabilising the new system. We’re now fairly confident in it so we’re going to start moving over the last of those clients to the new one. As we move over, your client will gradually start getting results from the new system.

Should be getting results from the new system automatically :)

**Comment by mattbdean** [comment]
Cool beans
