### ISSUE TITLE
DexArchiveMergerException with jitpack

### ISSUE THREAD

**Issue by KirkBushman** [mattbdean/JRAW#228]
Hi, 
I'm trying to use jitpack to get some features that won't be available until 1.1.0,
but when compiling I get the following error:

    Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
    > com.android.builder.dexing.DexArchiveMergerException: com.android.tools.r8.errors.CompilationError: Program type already present: 
    net.dean.jraw.RedditClient$happeningNow$res$1

I'am getting the lib from here: "com.github.mattbdean:JRAW:2aa33f4",
I've added: maven { url 'https://jitpack.io' }

I tried to turn off D8 Compiler but the same thing happens, I tried to clear and invalidate cache numerous times, but nothing.

Am I missing something or is there a chance that this problem is in the lib?

Thanks in advance

**Comment by mattbdean** [comment]
Have you included both JRAW and JRAW-Android?

**Comment by KirkBushman** [comment]
Yes I have

**Comment by mattbdean** [comment]
JRAW-Android has a dependency on JRAW. Try including only one of them.

**Comment by KirkBushman** [comment]
I see, 
I was trying to test #227, as you said to use:

    repositories {
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        compile 'com.github.mattbdean:JRAW:7077924'
    }

if you don't want to wait out for 1.1.0.

But at the same time half of my code uses JRAW-Android,
and it looks like I can't use both at the same time.

Is there a way to do this?

**Comment by mattbdean** [comment]
Try this:

```groovy
compile('net.dean.jraw:JRAW-Android:1.0.0') {
    exclude group: 'net.dean.jraw'
}
compile 'com.github.mattbdean:JRAW:7077924'
```

**Comment by KirkBushman** [comment]
Works, nice!

**Comment by mattbdean** [comment]
I've added this to JRAW-Android's [FAQ](https://github.com/mattbdean/JRAW-Android/blob/master/README.md#how-do-i-use-a-different-version-of-jraw-ie-from-jitpack)
