### ISSUE TITLE
Make submission .getBody() to return something

### ISSUE THREAD

**Issue by gochev** [mattbdean/JRAW#230]
Currently in case when the post is a not image/link we still dont get submission.getBody() its always null.

will be nice if it works the way how the RSS view works with the submissions to have a small snippet of the content, otherwise a listing is kinda tricky to be made (with titles only)

**Comment by Saketme** [comment]
This sounds like a behavior that your client should be doing and not the library. You can always detect the type of submission by using `Submission#getPostHint()`.

**Comment by mattbdean** [comment]
@Saketme It's part of [PublicContribution](https://github.com/mattbdean/JRAW/blob/master/lib/src/main/kotlin/net/dean/jraw/models/PublicContribution.kt#L17)
