### ISSUE TITLE
How can I check if a submission has an image or a video

### ISSUE THREAD

**Issue by mpivchev** [mattbdean/JRAW#232]
Do I have to check whether the submission link comes from imgur or somewhere else to find out if the submission has a picture, or does JRAW have some method to do that easily?

Currently, I have this to show imgur pictures, but what if a submission contains a picture that does not come from a site I compare?

```
     if (!submission.isSelfPost() && submission.getUrl().contains(IMGUR_LINK)) {
            Uri uri = Uri.parse(submission.getUrl());
            media.setImageURI(uri);
        }

```

**Comment by mattbdean** [comment]
See [`Submission.getPostHint()`](https://github.com/mattbdean/JRAW/blob/v1.0.0/lib/src/main/java/net/dean/jraw/models/Submission.java#L97)
