### ISSUE TITLE
getNsfw on Subreddit always returns null

### ISSUE THREAD

**Issue by 1blustone** [mattbdean/JRAW#239]
I'm trying to retrieve whether a subreddit is marked as NSFW to be able to remove them from a list (`over18 == true`), but the value of `getNsfw` seems to always be `null` (and consequently, `isNsfw` returns `false`.)

```kotlin
fun main(args: Array<String>) {
    val credentials = Credentials.userless(clientId, clientSecret, uuid)
    val client = OAuthHelper.automatic(OkHttpNetworkAdapter(userAgent), credentials)

    val sub = client.subreddit("nsfw").about()
    println(sub.nsfw) // null
    println(sub.isNsfw) // false
}
```

Testing this with an SFW subreddit (i.e. `r/Otters`) _also_ results in `getNsfw` returning `null`.

Note: Viewing `about` at `r/nsfw/about.json` reveals:
![image](https://user-images.githubusercontent.com/17903523/37413768-0376d54c-27a8-11e8-9e24-07cda73e143b.png)

which is interesting, since [both NSFW flags are annotated with `over_18`](https://github.com/mattbdean/JRAW/blob/master/lib/src/main/java/net/dean/jraw/models/Subreddit.java#L74) and not `over18`.

Edit 2: _Just_ to make sure it wasn't an inconsistency between the OAuth APIs and the user-accessible API, I logged the response body in an interceptor:

```kotlin
val ohClient = OkHttpClient.Builder()
        .addInterceptor {
            val res = it.proceed(it.request())
            res.body()?.source()?.let {
                it.request(Long.MAX_VALUE)
                println(it.buffer().clone().readString(Charsets.UTF_8))
            }
            res
        }
        .build()

client = OAuthHelper.automatic(OkHttpNetworkAdapter(userAgent, ohClient), credentials))
```

and it seems to be the same.

**Comment by mattbdean** [comment]
Probably a mistake on my part. Everywhere else in the API `over_18` is used.

**Comment by mattbdean** [comment]
`getNsfw()` was never supposed to be part of the public API so I've deprecated it.
