### ISSUE TITLE
NullPointerException on DefaultPaginator.next() due to Null Thumbnail Value

### ISSUE THREAD

**Issue by JoeCourtneyW** [mattbdean/JRAW#241]
When trying to get a paginator that contains a post with a null thumbnail, an npe will be thrown

Error message: https://pastebin.com/jijruUhv

**Comment by JacquesSmuts** [comment]
Is there any suggested workaround for this yet? I can't load the Front Page at all anymore, due to "Null Type Value."

**Comment by duffjones** [comment]
Just like to add that my frontpage, and anything else using DefaultPaginator is currently broken. Trying to do a workaround with BarebonesPaginator, which seems to be fine

**Comment by ClockVapor** [comment]
I'm having the same problem with the same stack trace as @JoeCourtneyW. Any progress on this?

**Comment by mattbdean** [comment]
What sorting are you using? I can't reproduce:

```kotlin
redditClient.subreddit("all").posts()
    .sorting(SubredditSort.NEW)
    .limit(100)
    .build()
    .accumulate(maxPages = 10)
```

**Comment by JoeCourtneyW** [comment]
@mattbdean I can't seem to reproduce the error myself, I believe it occured on subreddits that contained deleted posts. The deleted posts would then have a null thumbnail and throw the npe. I'm not sure though.

**Comment by mattbdean** [comment]
I've made `getThumbnail()` nullable. I've also added `Submission#hasThumbnail()` for convenience.
