### ISSUE TITLE
Is there a way to determine where the comment tree should display "Load more comments"?

### ISSUE THREAD

**Issue by mpivchev** [mattbdean/JRAW#246]
Currently, my comment tree only displays comments that Reddit originally provides, but I am not sure how to make it find the right place to show "load more comments". Does Reddit (or JRAW) provide any help with that?

I see that we have `#getReplies` and `#getMoreChildren`. What is the difference between them, when the children ARE the replies, or am I missing something?

**My test example:**

![1](https://user-images.githubusercontent.com/6960329/39411779-2469f300-4c11-11e8-9371-1aad7ab836d4.PNG)

**How it should be:**

![2](https://user-images.githubusercontent.com/6960329/39411795-62ad45e0-4c11-11e8-9ddc-f2d4c57e2e38.PNG)

Current code for loading comments:

```
// Request comments from submission...
// On success:
Iterator<CommentNode<PublicContribution<?>>> commentIterator = root.walkTree().iterator();

while (commentIterator.hasNext()) {
    CommentNode commentNode = commentIterator.next();
    CommentItem commentItem = new CommentItem(commentNode);

    commentItems.add(commentItem);

    // Add this "load more comments" item if you know where to put it:
    //commentItems.add(new LoadMoreCommentsItem());
}

((CommentsAdapter) commentsRV.getAdapter()).updateItems(commentItems);
```

**Comment by mattbdean** [comment]
In the second screenshot each "...load more comments" represents a `MoreChildren`. Here's the documentation:

```java
/**
 * A MoreChildren is a model used by reddit to represent comments that exist, but could not be presented in the response
 * due to the large amounts of other, higher priority comments already being shown in the thread. On the website, a
 * MoreChildren is represented by the text "load more comments (<em>x</em> replies)". The average user shouldn't have to
 * deal with this class directly as {@link net.dean.jraw.tree.CommentNode} will handle loading more comments for you.
 *
 * MoreChildren instances can appear anywhere in a comment tree except at the very root.
 */
```

**Comment by mpivchev** [comment]
Thanks for the information. I will get back to this in a few weeks

**Comment by mattbdean** [comment]
I'm going to close this for now, please let me know if you need any more help!

**Comment by mpivchev** [comment]
It says that CommentNode will handle loading more comments but it doesn't, and it doesn't show a "load more comments" item on its own. I am not sure how to add this myself, since these "load more comments" items have to appear in very specific places, like at the start of a new depth of comments, or previous depths.

This is what I currently have:
```
   Iterator<CommentNode<PublicContribution<?>>> commentIterator = root.walkTree().iterator();

                        root.visualize();

                        while (commentIterator.hasNext()) {
                            CommentNode commentNode = commentIterator.next();
                            CommentItem commentItem = new CommentItem(commentNode);

                            commentItems.add(commentItem);

                            if (commentNode.getDepth() > 1) {

                                if (commentNode.hasMoreChildren()) {
                                    commentItems.add(new LoadMoreCommentsItem(2));
                                }
                            }
```

**Comment by mpivchev** [comment]
I'm sorry, I really don't understand this.

Do I need to use your example for  this to work:
`Iterator<CommentNode<PublicContribution<?>>> commentIterator = root.walkTree().iterator();` which makes a proper comment tree but can't tell me if at the end of a specific node there should be more comments.

The problem is, it builds all the hierarchy but doesn't tell me at which point in it there should be more comments.

**Comment by mpivchev** [comment]
Figured it out. `getReplies` is the direct children which returns the children that are showing, while `hasMoreChildren` returns true if there are additional children that are hidden by the API. 

Took me more than I expected to figure it out :D
