### ISSUE TITLE
Issues obtaining user flair

### ISSUE THREAD

**Issue by cpobrien** [mattbdean/JRAW#250]
Hi!
I've been trying to scrape /r/dailyprogrammer, but I've been having trouble receiving flair text. From [this json](https://www.reddit.com/r/dailyprogrammer/comments/8g0iil/20180430_challenge_359_easy_regular_paperfold/dy7xbrm.json), it looks like author_flair_text ought to equal "-9 8", but it is null instead. I've provided example code to replicate the issue.

```   java
public void minimalCase() {
        RootCommentNode comments = client.submission("8g0iil").comments();
        comments.loadFully(client);
        Optional<CommentNode<Comment>> commentNode = comments.getReplies()
                .stream()
                .filter(comment ->
                        comment.getSubject()
                                .getId()
                                .equals("dy7xbrm"))
                .findFirst();
        commentNode.ifPresent(node -> {
            assert node.getSubject().getAuthorFlairText() != null;
            // should equal "-9 8"
        });
    }
```

I might be using the API wrong, as I only have a few days of experience with it. If so, what is the right way of getting user flair?

Thanks,
Connor

**Comment by mattbdean** [comment]
This is actually a bug. I had Moshi look for a property called `authorFlairText` instead of `author_flair_text`.

Can you confirm this is fixed?

```groovy
repositories {
    maven { url 'https://jitpack.io' }
}
dependencies {
    compile 'com.github.mattbdean:JRAW:4942855'
}
```
