### ISSUE TITLE
Accessing JSON used for constructing data models

### ISSUE THREAD

**Issue by saket** [mattbdean/JRAW#254]
Hey @mattbdean, I'm just updating to JRAW v1.0 and I have to say that this is fantastic work. I have one question -- I used to rely a lot on `Thing#getDataNode()` method for accessing custom fields that JRAW hasn't added in yet. 

Now that JRAW v1 does not lazily evaluate fields in data models anymore, is there still any other way to access the JSON that was used to create them?

**Comment by mattbdean** [comment]
Unfortunately right now there is not. I realize consumers might need to access properties not officially handled by JRAW and I plan on supporting it in v1.2.0 by forking [rharter/auto-value-moshi](https://github.com/rharter/auto-value-moshi). Right now the idea is to store unknown properties in a `Map<String, Object>` while deserializing and allow access to these properties via a `get(String key)` method.

**Comment by mattbdean** [comment]
With Moshi, any properties not registered by the model are thrown away during deserialization. The fork would add the ability to store those would-be-discarded properties and then allow access to them at a later time.

**Comment by saket** [comment]
I see. Moshi has built in codegen with v1.6. Did you get a chance to look at it?

**Comment by saket** [comment]
Makes sense. Familiarity > shiny new things.
