### ISSUE TITLE
How do you respond to a private message?

### ISSUE THREAD

**Issue by saket** [mattbdean/JRAW#255]
`AccountManager#reply()` previously used to accept `PrivateMessage`, which made it possible to reply to them. What's the alternative to this in v1.0? Is `InboxReference#compose()` what I'm supposed to use?

**Comment by mattbdean** [comment]
I must have forgotten that `POST /api/comment` also lets you reply to PMs. I'll add `InboxReference#reply`

**Comment by saket** [comment]
Ah okay. Do you also plan to introduce abstractions like `PrivateMessage` and `CommentMessage` again instead of just `Message`?

**Comment by mattbdean** [comment]
I don't think its necessary. The only difference between PrivateMessage and CommentMessage is two additional methods in CommentMessage. The new combined class and its `isComment()` method should be good enough to distinguish the two.

**Comment by saket** [comment]
There are more actually. There's `link_title` for comments and `replies` for private messages. But I'm okay having nullable functions for them for now.
