### ISSUE TITLE
Interactive OAuthHelper

### ISSUE THREAD

**Issue by koflin** [mattbdean/JRAW#257]
I am trying to get an access token for my webapp. I don't understand how I can do these three points listed in the wiki in one run.

1. Obtain an authorization URL using getAuthorizationUrl(Credentials, boolean, String...).
2. Point the user's browser to that URL and have the user login and then press 'accept' on the authentication form. The URL that the browser redirects to will be your app's redirect URI with some arguments in the query.
3. Provide this data as well as the same Credentials instance to OAuthHelper.onUserChallenge(String, Credentials). This method will parse the query arguments and report any errors. Once the response's integrity has been verified, a request to obtain the OAuth access code will be made and an instance of OAuthData retrieved.

**Comment by mattbdean** [comment]
I see you closed the issue, did you still need any help?

**Comment by koflin** [comment]
No I found it out by myself thanks for asking.
