### ISSUE TITLE
use .Json for JsonTokenStore

### ISSUE THREAD

**Issue by MeMeBigProgrammer** [mattbdean/JRAW#258]
This is pretty trivial, but it would be a good idea to have a note in the JsonFileTokenStore Documentation that the File name needs to have a .json extension instead of a .txt. Since when you try to retrieve Access tokens from a .txt, it will throw a Null pointer.

**Comment by mattbdean** [comment]
Can you provide an example?

**Comment by MeMeBigProgrammer** [comment]
Correction: It doesn't throw an NPE, it just acts as if the file is empty. 

let's say I have a file with all my tokens called token.tx, and I'm trying to persist my Access Tokens. I try to retrieve all the tokens and print out the Usernames.

`import java.io.File;
import java.util.List;

import net.dean.jraw.oauth.JsonFileTokenStore;

public class Example {

	private static final File file = new File("Token.txt");
	public static JsonFileTokenStore tokenStore = new JsonFileTokenStore(file);
	
	
	public static void main(String[]args) {
		System.out.println(tokenStore.size());
		List<String> usernames = tokenStore.getUsernames();
		usernames.forEach(System.out::println);
	}
	
	
}`

That code with token.txt having multiple valid tokens will print: 

`0`

I can't reveal the contents of token.txt because there are actual access tokens in there.

**Comment by mattbdean** [comment]
Please read the documentation

```java
/**
 * This class stores its data in a file encoded as JSON. It uses Moshi to persist and load data from that file.
 *
 * ```kt
 * val tokenStore = JsonFileTokenStore(someFile)
 *
 * // Read the already stored data from the file
 * tokenStore.load()
 *
 * // Make some changes (this is probably done by AuthManager)
 * tokenStore.storeRefreshToken("username", "foobar")
 *
 * // Save changes to disk
 * tokenStore.persist()
 * ```
 *
 * @see DeferredPersistentTokenStore
 */
```

**Comment by MeMeBigProgrammer** [comment]
Nevermind, guess I should have read the documentation more closely. By the way, thanks, JRAW is great for making Reddit Scripts quickly.
