### ISSUE TITLE
Switching RedditClient when AccountHelper#logout() is called

### ISSUE THREAD

**Issue by saket** [mattbdean/JRAW#260]
I just noticed that `AccountHelper#logout()` doesn't switch the reddit client. Is this intentional?

Edit: I'd be happy to contribute if you think we should update the `RedditClient`.

**Comment by mattbdean** [comment]
What do you mean exactly by "doesn't switch the reddit client?"

**Comment by saket** [comment]
`AccountHelper` calls `switch()` with a new `RedditClient` when methods like `switchToUserless()` or `switchToUser()` are called. I was wondering if `logout()` should internally call `switchToUserless()` or is this something you want the client to decide?

**Comment by mattbdean** [comment]
I don't think it should. It isn't guaranteed that the client will want to immediately switch to userless auth. If they do, its just one more line of code.

**Comment by saket** [comment]
Makes sense.
