### ISSUE TITLE
SearchPaginator limit number while querying

### ISSUE THREAD

**Issue by sc-gurcha** [mattbdean/JRAW#281]
While using SearchPaginator I used these lines:

`SearchPaginator p = builder1.query("abbott").limit(100).build();`

and

`List<Submission> submissions = p.accumulateMerged(10);`

What are the numbers in limit() and in accumulateMerged(), also how to get the most recent submissions? I was looking [into this](https://github.com/mattbdean/JRAW/issues/212#issuecomment-356431419) but the `sort()` is not available in Java.

Thank you :)

**Comment by mattbdean** [comment]
`limit(int n)` instructs reddit to return a maximum of `n` objects per page. `accumulateMerged(int m)` will fetch `m` pages and combine (merge) them into one list.

Use `sorting()` instead of `sort()`. I made a mistake on that GitHub comment.

**Comment by sc-gurcha** [comment]
So is it like a bulk combine. In the above example, 100 objects will be retrieved and they will be merged 10 at a time into the final list?
I will look into sorting().
Thank you
