### ISSUE TITLE
Ability to disable caching

### ISSUE THREAD

**Issue by hobbs** [mattbdean/JRAW#33]
I'd like to be able to disable caching. When I poll for "new" comments, I only see an updated response every 2-3 minutes while using JRAW. If I hit the same URL in my browser I see it continually updated.

Looks like OKHttp's CacheControl should allow for this, but not exactly sure where that should be used in JRAW. If you have any tips let me know, I'd be glad to create a pull request.

**Comment by hobbs** [comment]
Thanks for the fix, but it doesn't work for me unfortunately. I forked JRAW and tried something similar and it didn't work either. I wonder if the underlying android networking libs are doing some kind of caching? The only way I've been about to do it is by adding a cache-busting GET param on the request :(

**Comment by thatJavaNerd** [comment]
Can you post the code that's producing this and its HTTP logs?

**Comment by saket** [comment]
@mattbdean what's the current way of disabling cache altogether in Jraw's http client?

**Comment by mattbdean** [comment]
That's handled through the OkHttpNetworkAdapter:

```kotlin
val okHttpClient = OkHttpClient.Builder()
    .cache(null)
    .build()
val networkAdapter = OkHttpNetworkAdapter(http = okHttpClient, ...)
val authHelper = OAuthHelper.interactive(okHttpClient, ...)
```

**Comment by saket** [comment]
Got it, thank you!
